### ISSUE TITLE
[Sohyun] 헤더(상단 네이게이션 바) 구현, scss 수정(mixin,media)

### ISSUE THREAD

**Issue by thgus5335** [thgus5335/DoThisDoThat#6]
## 기능명
헤더(상단 네이게이션 바) 구현

## 구현 목표
- [x] 헤더(상단 네이게이션 바) UI 구현
- [x] 멤버 프로필을 누르면 드롭 다운으로 멤버 목록
- [x] 오른쪽 이름을 누르면 드롭 다운으로 '로그아웃' 버튼, '내정보' 버튼 '내 대시보드' 버튼
- [x]  '로그아웃' 버튼을 클릭하면 `/` 페이지로 이동
- [x]  '내 정보' 버튼을 클릭하면 `/mypage` 페이지로 이동
- [x]  '내 대시보드' 버튼을 클릭하면 `/mydashboard` 페이지로 이동
- [x] mixin.scss 수정, media.scss 추가

## 특이 사항
- mixin 변수 매개변수 사용할 수도 있더라구요! 수정해놓겠습니도

  ```scss
  @mixin text-xs($weight) {
      font-size: 12px;
      font-weight: $weight;
  }
  ```
